
name: C/C++ build

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup
      uses: lukka/get-cmake@latest

    - name: Build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-multi-vcpkg'
        configurePresetAdditionalArgs: "['-DENABLE_YOUR_FEATURE=1']"
        buildPreset: 'ninja-multi-vcpkg'
        buildPresetAdditionalArgs: "['--config Release']"
        testPreset: 'ninja-multi-vcpkg'
        testPresetAdditionalArgs: "['--config Release']"

    #- name: Run Tests (if applicable)
    #  run: cd build && ctest || true

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Artifact-${{ matrix.config.os }}
        path: build/
