
name: C/C++ build

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup compiler on Ubuntu/MacOS
      if: runner.os != 'Windows'
      run: |
        sudo apt-get update -y || true
        sudo apt-get install -y build-essential cmake || true

    - name: Setup compiler on Windows
      if: runner.os == 'Windows'
      run: choco install cmake -y --no-progress
        
    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Preset on Ubuntu/MacOS
      if: runner.os != 'Windows'
      run: cmake --preset release-unix # cmake --build build

    - name: Preset on Windows
      if: runner.os == 'Windows'
      run: cmake --preset release-vs

    - name: Build
      run: cmake --build build

    - name: Run Tests (if applicable)
      run: cd build && ctest || true

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Artifact-${{ matrix.config.os }}
        path: build/
